// Paint color names from major brands - unique and sentence-producing names
export const PAINT_COLORS = [
  // Unique sentence-producing colors
  'Storm', 'Lightning', 'Heart', 'To', 'Sweet', 'Juliet', 'Patience', 'Paparazzi',
  'Evening', 'Slipper', 'First', 'Light', 'Morning', 'Glory', 'Midnight', 'Blue',
  'Silver', 'Lining', 'Golden', 'Hour', 'Twilight', 'Zone', 'Secret', 'Garden',
  'Hidden', 'Treasure', 'Gentle', 'Rain', 'Soft', 'Whisper', 'Silent', 'Night',
  'Peaceful', 'Moment', 'Quiet', 'Time', 'Perfect', 'Storm', 'Wild', 'Rose',
  'True', 'Love', 'Forever', 'Young', 'Simply', 'White', 'Pure', 'Joy',
  'Happy', 'Place', 'Safe', 'Harbor', 'Warm', 'Welcome', 'Open', 'Door',
  'Fresh', 'Start', 'New', 'Beginning', 'Bright', 'Future', 'Sweet', 'Dreams',
  'Lazy', 'Sunday', 'Easy', 'Living', 'Carefree', 'Spirit', 'Free', 'Bird',
  'Ocean', 'Breeze', 'Sea', 'Salt', 'Beach', 'House', 'Sand', 'Dollar',
  'Coral', 'Reef', 'Deep', 'Water', 'Navy', 'Pier', 'Harbor', 'Mist',
  'Foggy', 'Morning', 'Misty', 'Mountain', 'High', 'Peak', 'Summit', 'View',
  'Valley', 'Green', 'Forest', 'Path', 'Woodland', 'Walk', 'Nature', 'Trail',
  'Garden', 'Party', 'Spring', 'Bloom', 'Cherry', 'Blossom', 'Rose', 'Petal',
  'Lavender', 'Field', 'Violet', 'Sky', 'Purple', 'Haze', 'Plum', 'Perfect',
  'Berry', 'Sweet', 'Grape', 'Vine', 'Wine', 'Country', 'Burgundy', 'Velvet',
  'Royal', 'Purple', 'Majestic', 'Crown', 'King', 'Size', 'Queen', 'Anne',
  'Victorian', 'Rose', 'Antique', 'White', 'Vintage', 'Charm', 'Classic', 'Gray',
  'Timeless', 'Beauty', 'Elegant', 'Touch', 'Refined', 'Taste', 'Sophisticated', 'Style',
  'Modern', 'Art', 'Contemporary', 'Edge', 'Urban', 'Chic', 'City', 'Lights',
  'Downtown', 'Brown', 'Metro', 'Gray', 'Concrete', 'Jungle', 'Steel', 'Blue',
  'Iron', 'Gate', 'Stone', 'Wall', 'Brick', 'House', 'Colonial', 'White',
  'Country', 'Side', 'Farm', 'House', 'Barn', 'Red', 'Rustic', 'Charm',
  'Weathered', 'Wood', 'Driftwood', 'Gray', 'Aged', 'Copper', 'Antique', 'Bronze',
  'Vintage', 'Gold', 'Old', 'World', 'Ancient', 'Stone', 'Historic', 'Tan',
  'Desert', 'Sand', 'Sahara', 'Sun', 'Sunset', 'Orange', 'Sunrise', 'Yellow',
  'Golden', 'Gate', 'Honey', 'Wheat', 'Butter', 'Cream', 'Vanilla', 'Ice',
  'Sugar', 'Cookie', 'Caramel', 'Latte', 'Mocha', 'Java', 'Coffee', 'Bean',
  'Espresso', 'Shot', 'Dark', 'Roast', 'French', 'Press', 'Turkish', 'Delight',
  'Chocolate', 'Truffle', 'Cocoa', 'Powder', 'Hot', 'Fudge', 'Brown', 'Sugar',
  'Cinnamon', 'Stick', 'Nutmeg', 'Spice', 'Ginger', 'Snap', 'Pumpkin', 'Pie',
  'Apple', 'Cider', 'Autumn', 'Leaves', 'Fall', 'Harvest', 'October', 'Sky',
  'November', 'Rain', 'Winter', 'White', 'Snow', 'Fall', 'Ice', 'Blue',
  'Frost', 'Bite', 'Arctic', 'White', 'Polar', 'Bear', 'Glacier', 'Blue',
  'Alaska', 'Sky', 'Northern', 'Lights', 'Aurora', 'Green', 'Emerald', 'Isle',
  'Irish', 'Green', 'Shamrock', 'Shake', 'Mint', 'Julep', 'Lime', 'Light',
  'Citrus', 'Burst', 'Lemon', 'Drop', 'Sunshine', 'Yellow', 'Daffodil', 'White',
  'Daisy', 'Chain', 'Buttercup', 'Yellow', 'Canary', 'Song', 'Bird', 'Bath',
  'Feather', 'Light', 'Angel', 'Wing', 'Cloud', 'Nine', 'Heaven', 'Sent',
  'Divine', 'White', 'Celestial', 'Blue', 'Star', 'Light', 'Moon', 'Beam',
  'Sun', 'Ray', 'Day', 'Break', 'Dawn', 'Light', 'Morning', 'Dew',
  'Fresh', 'Mint', 'Cool', 'Breeze', 'Chill', 'Out', 'Relax', 'Mode',
  'Zen', 'Garden', 'Peace', 'Full', 'Calm', 'Waters', 'Still', 'Life',
  'Serene', 'Blue', 'Tranquil', 'Pond', 'Quiet', 'Harbor', 'Restful', 'Gray',
  'Sleepy', 'Hollow', 'Dream', 'Catcher', 'Night', 'Owl', 'Hoot', 'Owl',
  'Wise', 'Sage', 'Clever', 'Fox', 'Sly', 'Gray', 'Wolf', 'Gray',
  'Bear', 'Brown', 'Grizzly', 'Peak', 'Mountain', 'High', 'Alpine', 'White',
  'Snow', 'Cap', 'Ice', 'Cap', 'Frozen', 'Lake', 'Crystal', 'Clear',
  'Diamond', 'White', 'Pearl', 'White', 'Ivory', 'Tower', 'Castle', 'Gray',
  'Knight', 'Armor', 'Silver', 'Sword', 'Blade', 'Runner', 'Fast', 'Track',
  'Race', 'Car', 'Speed', 'Demon', 'Red', 'Hot', 'Fire', 'Engine',
  'Flame', 'Red', 'Burning', 'Love', 'Passion', 'Fruit', 'Cherry', 'Red',
  'Ruby', 'Red', 'Garnet', 'Stone', 'Precious', 'Gem', 'Jewel', 'Tone',
  'Rich', 'Burgundy', 'Deep', 'Wine', 'Merlot', 'Red', 'Cabernet', 'Red',
  'Blush', 'Pink', 'Rose', 'Gold', 'Copper', 'Penny', 'Bronze', 'Medal',
  'Gold', 'Rush', 'Treasure', 'Hunt', 'Hidden', 'Gold', 'Secret', 'Stash',
  'Lucky', 'Charm', 'Four', 'Leaf', 'Clover', 'Green', 'Grass', 'Green',
  'Meadow', 'Green', 'Sage', 'Brush', 'Desert', 'Sage', 'Olive', 'Branch',
  'Peace', 'Dove', 'White', 'Dove', 'Gentle', 'Spirit', 'Kind', 'Heart',
  'Tender', 'Touch', 'Soft', 'Pink', 'Baby', 'Pink', 'Cotton', 'Candy',
  'Sweet', 'Pea', 'Sugar', 'Plum', 'Fairy', 'Tale', 'Story', 'Book',
  'Page', 'Turner', 'Book', 'Worm', 'Library', 'Gray', 'Scholar', 'Green',
  'Ivy', 'League', 'Prep', 'School', 'Old', 'School', 'Vintage', 'Denim',
  'Blue', 'Jean', 'Jacket', 'Blue', 'Denim', 'Wash', 'Faded', 'Blue',
  'Sky', 'Blue', 'Baby', 'Blue', 'Powder', 'Blue', 'Periwinkle', 'Blue',
  'Cornflower', 'Blue', 'Azure', 'Sky', 'Cerulean', 'Blue', 'Teal', 'Blue',
  'Turquoise', 'Water', 'Aqua', 'Marine', 'Caribbean', 'Blue', 'Tropical', 'Sea',
  'Island', 'Blue', 'Lagoon', 'Blue', 'Paradise', 'Found', 'Oasis', 'Green',
  'Palm', 'Tree', 'Coconut', 'Grove', 'Banana', 'Leaf', 'Jungle', 'Green',
  'Rain', 'Forest', 'Moss', 'Green', 'Fern', 'Green', 'Hunter', 'Green',
  'Pine', 'Tree', 'Ever', 'Green', 'Cedar', 'Chest', 'Mahogany', 'Wood',
  'Walnut', 'Brown', 'Chestnut', 'Brown', 'Hazel', 'Nut', 'Almond', 'Cream',
  'Pecan', 'Pie', 'Maple', 'Syrup', 'Honey', 'Comb', 'Bee', 'Hive',
  'Busy', 'Bee', 'Worker', 'Bee', 'Queen', 'Bee', 'Bumble', 'Bee',
  'Butterfly', 'Blue', 'Dragon', 'Fly', 'Lady', 'Bug', 'Love', 'Bug',
  'June', 'Bug', 'Fire', 'Fly', 'Lightning', 'Bug', 'Glow', 'Worm',
  'Earth', 'Worm', 'Book', 'Mark', 'Water', 'Mark', 'Trade', 'Mark',
  'Question', 'Mark', 'Exclamation', 'Point', 'Starting', 'Point', 'End', 'Point',
  'High', 'Point', 'Low', 'Point', 'Turning', 'Point', 'Breaking', 'Point',
  'Boiling', 'Point', 'Melting', 'Point', 'Freezing', 'Point', 'Flash', 'Point',
  'Match', 'Point', 'Game', 'Point', 'Score', 'Board', 'Leader', 'Board',
  'Surf', 'Board', 'Skate', 'Board', 'Snow', 'Board', 'Clip', 'Board',
  'Key', 'Board', 'Dash', 'Board', 'Card', 'Board', 'Cup', 'Board',
  'Side', 'Board', 'Base', 'Board', 'Head', 'Board', 'Tail', 'Gate',
  'Front', 'Gate', 'Back', 'Gate', 'Garden', 'Gate', 'Golden', 'Gate',
  'Water', 'Gate', 'Flood', 'Gate', 'Starting', 'Gate', 'Finish', 'Line',
  'Goal', 'Line', 'Touch', 'Down', 'Show', 'Down', 'Break', 'Down',
  'Melt', 'Down', 'Count', 'Down', 'Sun', 'Down', 'Moon', 'Rise',
  'Sun', 'Rise', 'High', 'Rise', 'Low', 'Rise', 'Early', 'Bird',
  'Night', 'Hawk', 'Sea', 'Hawk', 'Black', 'Hawk', 'War', 'Hawk',
  'Tomahawk', 'Red', 'Mohawk', 'Brown', 'Falcon', 'Gray', 'Eagle', 'Eye',
  'Bird', 'Eye', 'Bulls', 'Eye', 'Private', 'Eye', 'Evil', 'Eye',
  'Third', 'Eye', 'Blind', 'Side', 'Bright', 'Side', 'Dark', 'Side',
  'Flip', 'Side', 'Up', 'Side', 'Down', 'Side', 'Out', 'Side',
  'In', 'Side', 'Along', 'Side', 'Beside', 'Manner', 'Road', 'Side',
  'Hill', 'Side', 'Mountain', 'Side', 'Lake', 'Side', 'River', 'Side',
  'Water', 'Side', 'Fire', 'Side', 'Bed', 'Side', 'Table', 'Side',
  'Court', 'Side', 'Ring', 'Side', 'Pool', 'Side', 'Beach', 'Side'
] as const;

export type PaintColor = typeof PAINT_COLORS[number];

export function isValidWord(word: string): boolean {
  return PAINT_COLORS.some(color => color.toLowerCase() === word.toLowerCase());
}

export function getRandomWords(count: number): string[] {
  const shuffled = [...PAINT_COLORS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
